import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { getSessionUser } from "@/lib/auth-guard";
import { cleanString, errorJson, readJsonObject, tooMany, unauthorized } from "@/lib/http";
import { rateLimit } from "@/lib/rate-limit";
import { ASSET_TYPES } from "@/lib/constants";
import { MAX_ASSETS_PER_MEMBER, adoptAssetPhotos, assetSummarySelect } from "@/lib/assets";
import { StorageError } from "@/lib/storage";
import { writeAudit } from "@/lib/audit";

/** The signed-in member's own assets (with their QR reference IDs). */
export async function GET() {
  try {
    const user = await getSessionUser();
    if (!user) return unauthorized();
    const assets = await prisma.asset.findMany({ where: { userId: user.id }, select: assetSummarySelect, orderBy: { createdAt: "desc" } });
    return NextResponse.json(assets);
  } catch (error) {
    console.error("Member assets fetch error:", error);
    return errorJson("Failed to load assets", 500);
  }
}

/** Members register their own assets; the QR reference ID is generated by the database, never supplied. */
export async function POST(request: Request) {
  try {
    const user = await getSessionUser();
    if (!user) return unauthorized();
    if (!(await rateLimit("profileWrite", user.id)).success) return tooMany();

    const body = await readJsonObject(request);
    if (!body) return errorJson("Invalid request body", 400);

    const identifier = cleanString(body.identifier, 100);
    const assetType = body.assetType;
    if (!identifier) return errorJson("Identifier is required (licence plate or serial number)", 400);
    if (typeof assetType !== "string" || !(ASSET_TYPES as readonly string[]).includes(assetType)) return errorJson("Invalid asset type", 400);

    if ((await prisma.asset.count({ where: { userId: user.id } })) >= MAX_ASSETS_PER_MEMBER) {
      return errorJson(`You can register up to ${MAX_ASSETS_PER_MEMBER} assets. Remove one first, or contact the C2 administrator.`, 400);
    }

    let photos;
    try {
      photos = await adoptAssetPhotos(body, user.id);
    } catch (error) {
      if (error instanceof StorageError) return errorJson(error.message, 400);
      throw error;
    }

    const asset = await prisma.asset.create({ data: { userId: user.id, assetType, identifier, ...photos }, select: assetSummarySelect });
    await writeAudit(request, user.id, "ASSET_REGISTERED", `${assetType} ${identifier} (added by owner)`, {
      assetType: { from: null, to: assetType },
      identifier: { from: null, to: identifier },
    });
    return NextResponse.json(asset, { status: 201 });
  } catch (error) {
    console.error("Member asset create error:", error);
    return errorJson("Failed to add asset", 500);
  }
}
